org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft version (shared by all subprojects)
minecraft_version=26.3
loom_version=1.17-SNAPSHOT

# Fabric
loader_version=0.19.5
fabric_api_version=0.160.7+26.3

# NeoForge
neo_version=26.3.0.4-beta
minecraft_version_range=[26.3]
neogradle_version=7.1.39

# Mod
mod_version=0.3
maven_group=ru.skybuilder1717
archives_base_name=stickers
