modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "stickers"
    version = "${version}"
    displayName = "Stickers"
    description = "Stickers for your HUD."
    logoFile = "assets/stickers/icon.png"

[[dependencies.stickers]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stickers]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
